### ISSUE TITLE
Could not get the reflection type for DbContext CodeGeneration 3.1.3 when Scalfording API

### ISSUE THREAD

**Issue by leonardolondono** [dotnet/Scaffolding#1344]
## Note: If filing an issue related to using Scaffolding within Microsoft Visual Studio, please file an issue on the Microsoft Developer Community instead of here. This can be accomplished from Visual Studio by clicking on Help > Send Feedback, and choosing the appropriate action.

I´m working with the latest version of VS 2019 Version 16.6.0, .Net Core 3.1 and CodeGenerator 3.1.3

When I´m trying to create a Web API using scaffolding, I´m getting the following error:

> Could not get the reflection type for DbContext : DBProdModels.DBProdContext
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)

**Comment by deepchoudhery** [comment]
Hey,
Are you still running into this issue?

**Comment by deepchoudhery** [comment]
fixed for dotnet-scaffold, closing., please use the new 'dotnet-scaffold' tool. Blog [here](https://devblogs.microsoft.com/dotnet/introducing-dotnet-scaffold/)
