### ISSUE TITLE
.NET 6.0 GA  can't have #region on first line of Program.cs file

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/Scaffolding#1626]
This is such a rare edge case feel free to close.

```
dotnet --version
6.0.100
```

To reproduce the problem.

`dotnet new webapp -o RazorPagesMovie`

Add `#region` to generated code:

```
#region snippet_all
var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddRazorPages();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseStaticFiles();

app.UseRouting();

app.UseAuthorization();

app.MapRazorPages();

app.Run();
#endregion
```

Create a `Models` folder and add the following movie model

```
using System.ComponentModel.DataAnnotations;

namespace RazorPagesMovie.Models
{
    public class Movie
    {
        public int ID { get; set; }
        public string Title { get; set; } = string.Empty;

        [DataType(DataType.Date)]
        public DateTime ReleaseDate { get; set; }
        public string Genre { get; set; } = string.Empty;
        public decimal Price { get; set; }
    }
}
```

Scaffold with CLI
```
dotnet tool uninstall -g dotnet-aspnet-codegenerator
dotnet tool install -g dotnet-aspnet-codegenerator
dotnet tool uninstall -g dotnet-ef
dotnet tool install --global dotnet-ef
dotnet add package Microsoft.EntityFrameworkCore.Design
dotnet add package Microsoft.EntityFrameworkCore.SQLite
dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design
dotnet add package Microsoft.EntityFrameworkCore.SqlServer
dotnet-aspnet-codegenerator razorpage -m Movie -dc RazorPagesMovieContext -udl -outDir Pages/Movies --referenceScriptLibraries -sqlite
```

Expected result: Scaffolds `Movie` class
Actual result:
```
Building project ...
Finding the generator 'razorpage'...
Running the generator 'razorpage'...

Minimal hosting scenario!
Generating a new DbContext class 'RazorPagesMovieContext'
Attempting to compile the application in memory with the added DbContext.
There was an error creating a DbContext :c:\tmp\11\RazorPagesMovie\Program.cs(9,65): error CS1733: Expected expression
c:\tmp\11\RazorPagesMovie\Program.cs(9,65): error CS1026: ) expected
c:\tmp\11\RazorPagesMovie\Program.cs(9,65): error CS1002: ; expected
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
RunTime 00:00:15.01
```

Scaffold with VS 2022 - same error

```
---------------------------
Microsoft Visual Studio
---------------------------
Error

There was an error running the selected code generator:

'There was an error creating a DbContext :C:\tmp\11\RazorPagesMovie\2\RazorPagesMovie\Program.cs(10,65): error CS1733: Expected expression
C:\tmp\11\RazorPagesMovie\2\RazorPagesMovie\Program.cs(10,65): error CS1026: ) expected
C:\tmp\11\RazorPagesMovie\2\RazorPagesMovie\Program.cs(10,65): error CS1002: ; expected'
---------------------------
OK   
---------------------------

```

***Work around - Fix***
Remove all the regions

**Comment by Rick-Anderson** [comment]
Closing since I'm the only one who cares about this and I can work around it.

**Comment by Rick-Anderson** [comment]
@deman-Innotractor I'll reopen if you can make a case for investing in fixing this extreme edge case.

**Comment by deman-Innotractor** [comment]
I don't have any projects left that are using regions (in the program.cs) so for me it isn't a big issue. The workaround is removing the regions, and adding them back later should be easy.
