### ISSUE TITLE
"Path not found" error when scaffolding in a project that references Microsoft.AspNetCore.Identity

### ISSUE THREAD

**Issue by Extragorey** [dotnet/Scaffolding#1713]
### Issue

The following error is thrown when running the command `dotnet aspnet-codegenerator identity -lf`.

```
[Trace]: Command Line: identity -lf
    Building project ...
    [Trace]: Command Line: --no-dispatch --port-number 64193 identity -lf --dispatcher-version 6.0.0+cc9d1f5236d926269a0471042f72bf83b498509c
    Scaffolding failed.
    The path is empty. (Parameter 'path')
    [Trace]:    at System.IO.Path.GetFullPath(String path)
       at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
       at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
       at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
       at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
       at Microsoft.VisualStudio.Web.CodeGeneration.Msbuild.ProjectContextWriter.GetScaffoldingAssemblies(IEnumerable`1 dependencies)
       at Microsoft.DotNet.Scaffolding.Shared.ProjectModel.ProjectContextExtensions.AddPackageDependencies(IProjectContext projectInformation, String projectAssetsFile)
       at Microsoft.VisualStudio.Web.CodeGeneration.Design.Program.<>c__DisplayClass4_0.<<Execute>b__0>d.MoveNext()
    RunTime 00:00:02.43
```

### Reproduction Steps

1) Create a new project using the template "ASP.NET Core Web App (Model-View-Controller)" targeting .NET 6.0 and with the authentication type set to Individual Accounts.
2) Add the following Nuget package: 
    - Microsoft.VisualStudio.Web.CodeGeneration.Design (to support scaffolding)
3) Save all files (Ctrl + Shift + S) and rebuild the solution.
4) At this point, open cmd to the project file's directory and run `dotnet aspnet-codegenerator identity -lf` to ensure the list of available Identity views for scaffolding is shown successfully.
5) Add the following Nuget package:
    - Microsoft.AspNetCore.Identity
6) Save all files (Ctrl + Shift + S) and rebuild the solution.
7) Try to re-run the command `dotnet aspnet-codegenerator identity -lf` and the above error should occur.

### Environment Info

**Target framework:** .NET 6.0
**IDE:** Visual Studio 2022 17.0.1
**Operating system:** Windows Server 2016 Standard

Issue originally posted [on StackOverflow](https://stackoverflow.com/questions/70119631/aspnet-codegenerator-error-path-is-empty) (by me).

**Comment by anghelvalentin** [comment]
I have the same issue. Did you manage to solve it?

**Comment by Extragorey** [comment]
Yup, don't reference Microsoft.AspNetCore.Identity. xD
But it wasn't actually required as a direct reference in my case; I could
install the Microsoft.AspNetCore.Identity.EntityFrameworkCore nuget package
instead, and that worked.

**Comment by anghelvalentin** [comment]
I have written a tutorial about adding identity to an existing ASP.NET application and I have also presented the solution for this bug [https://programmingcsharp.com/implement-identity-on-existing-asp-project/](https://programmingcsharp.com/implement-identity-on-existing-asp-project/)

**Comment by JRoxellin** [comment]
anghelvalentin muchas gracias me salvaste la vida ese error tan pequeño me llevo a perder la cabeza muchas graciassss
