### ISSUE TITLE
Getting error when scaffolding empty razor page

### ISSUE THREAD

**Issue by dogancignakli** [dotnet/Scaffolding#1832]
I ran this code to create Empty model with custom name and Page model. cshtml file was created but page model was not
`dotnet aspnet-codegenerator razorpage Delete Empty -udl -outDir Pages/Restaurants/`

Error Message:
'Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Razor.RazorPageGeneratorTemplateModel2' does not contain a definition for 'NullableEnabled'
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)

**Comment by vijayrkn** [comment]
This should be fixed in the latest version.
