### ISSUE TITLE
Identity Scaffold Error for .net core 7

### ISSUE THREAD

**Issue by ainmor** [dotnet/Scaffolding#2257]
Hello support,

I am trying to scaffold the identity for my asp.net core 7 web application. I am using the SQL Server as Database, during scaffold I am getting error as "There was an error running the selected code generator:; "Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Identity.Id entityGeneratorTemplateMode2" does not contain a definition for 'UseSQLite'" 

Would be great if you have solution around this issue. 

Thank you in advance.

**Comment by deepchoudhery** [comment]
Hey,
Are you using VS or the command line?
We had this issue with the 7.0.2 but fixed it in the 7.0.3 package. Could you confirm you are using the latest `Microsoft.VisualStudio.Web.CodeGeneration.Design`?

Also another workaround (in case) is to use the command line (if not using) to scaffold identity:

- Install the dotnet tool by being in the project folder (with the .csproj file):
  - dotnet tool install dotnet-aspnet-codegenerator -g
- use dotnet-aspnet-codegenerator identity -sqlite which will scaffold out all identity files

**Comment by AlexZeitler** [comment]
I'm facing the same issue using version `7.0.5` using it both as global or local tool.

**Comment by AlexZeitler** [comment]
Just got it working: I had a `Startup.cs` in the project folder. Deleting the `Startup.cs` fixed it.

**Comment by ZepedaJake** [comment]
> Just got it working: I had a `Startup.cs` in the project folder. Deleting the `Startup.cs` fixed it.

Thanks so much. Just ran into this and this was the only solution I could find that worked.

**Comment by deepchoudhery** [comment]
Hey,
We are reworking some of the scaffolders to avoid these issues. Let me know if this still persists.

**Comment by nguyentuananh921** [comment]
I still have error with Identity Scaffold on net8. I can't user Scaffold to create Identity.

**Comment by magiak** [comment]
Hi, I have the same problem with Microsoft.VisualStudio.Web.CodeGeneration.Design 7.0.10

**Comment by b5white** [comment]
> I still have error with Identity Scaffold on net8. I can't use Scaffold to create Identity.

I had this problem in 7, so upgraded to 8. Still have this problem in CodeGeneration.Design 8.0.0. I do not have a Startup.cs in the project file. 

Same result from using the CLI
PM> dotnet-aspnet-codegenerator identity --force
Building project ...
Finding the generator 'identity'...
Running the generator 'identity'...
No database provider found. Using 'SqlServer' by default for new DbContext creation!
dotnet-aspnet-codegenerator : 'Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Identity.IdentityGeneratorTemplateModel2' does not 
contain a definition for 'UseSQLite'
At line:1 char:1
+ dotnet-aspnet-codegenerator identity --force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ('Microsoft.Visu...for 'UseSQLite':String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
This generates the cs files but not the cshtml files.

**Comment by MartinZ17** [comment]
Hello, I have the same issue in 7. My packages are upgraded to the latest 7 version (which is 7.0.15). Any solutions so far?

**Comment by deepchoudhery** [comment]
Hmmm I'm wondering if some of the related nuget packages are stale (Microsoft.VisualStudio.CodeGeneration.Design in particular). Would you mind clearing all `Microsoft.VisualStudio.WebCodeGeneration.*` packages from your nuget installation [location ](https://learn.microsoft.com/en-us/nuget/reference/nuget-config-file#:~:text=The%20location%20of%20the%20default%20global%20packages%20folder.%20The%20default%20is%20%25userprofile%25%5C.nuget%5Cpackages%20(Windows)%20or%20~/.nuget/packages%20(Mac/Linux).) 

Then update the global tool `dotnet-aspnet-codegenerator` and install the latest `Microsoft.VisualStudio.CodeGeneration.Design` for the particular target framework. 

Apologies for all these extra steps but would help track down the issue.

**Comment by MartinZ17** [comment]
I tried the instructions, but the result is same.

**Comment by chrisdyck** [comment]
I am having the same issue. If I start from scratch, it works fine. With a Data Context that inherits IdentityDbContext<ApplicationUser>, for example, the Identity Scaffolder dialog throws the error.

**Comment by MartinZ17** [comment]
Update: I migrate my project to .NET 8 and still the problem is there.

'Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Identity.IdentityGeneratorTemplateModel2' does not contain a definition for 'UseSQLite'

**Comment by deepchoudhery** [comment]
Hmmm looking at it again today, will try to have a fix very soon. Thanks for the patience.

**Comment by guyrish** [comment]
Any movement on this ticket? It's become a bit of a sore spot for us.

**Comment by benedek1** [comment]
@guyrish @deepchoudhery  Renaming the "Startup.cs" to "ServiceExtensions" fixed the issue for me. I have a BLL project and a separate ASP.NET Core project , i reference the BLL in my Core project and thats itm it lets me use the extension methods like: builder.Services.AddRepositories()

**Comment by itsmeLukas** [comment]
Same problem with ASP.NET Core 8,
Update all packages to the latest versions and then rebuilt solution.
It works for me.

**Comment by ashutoshvyas** [comment]
Updated all packages to latest version. Still facing issues. Tried with .NET CLI and it raises same issue

'Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Identity.IdentityGeneratorTemplateModel2' does not contain a definition for 'UseSQLite'

BTW I am not even using SQLite but am using SQL Server.

**Comment by acnicholls** [comment]
I have a context that inherits from IdentityContext, and even renaming `Startup.cs` to `TempStartup.cs`, I can't get past this error.  I even tried allowing the scaffolder to create a new context and user type, no love, same error

**Comment by ttugates** [comment]
I am experiencing this on .NET 8.  Will try a some of the solutions in this issue and update here if any solve.

**Comment by TimBoonstra** [comment]
I'm experiencing the same issue when using asp.net core 8  identity when i have my Database Context in another project file and i'm using SqlServer. 
I have to copy the DBContext file and user model to the main project and run it there. Then it will succefully generate the file(s)

.Net 8
dotnet-aspnet-codegenerator  9.0.0
Microsoft.VisualStudio.Web.CodeGeneration.Design  9.0.0

Command i'm running in the main project
dotnet aspnet-codegenerator identity -dc Namespace.MyDBContext -gl -dbProvider sqlserver

**Comment by TimBoonstra** [comment]
> Experiencing this in .Net 8
> 
> "There was an error running the selected code generator:; "Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Identity.Id entityGeneratorTemplateMode2" does not contain a definition for 'UseSQLite'"
> 
> Cause seems to be having the DbContext that `: IdentityDbContext` in a different Project.
> 
> Workaround is to move it back to the project you are scaffolding to (API w Identity).
> 
> Appears this is a tooling issue and you can move the DbContext back when finished and rest works.


I can confirm this, i'm running into the same issue in my project and used the same workaround to generate the files.
