### ISSUE TITLE
Scaffolding fails with partial methods an source generator

### ISSUE THREAD

**Issue by VMelnalksnis** [dotnet/Scaffolding#2290]
### Describe the bug

When trying to scaffold identity pages in a project that contains `GeneratedRegex` it fails with `Failed to compile the project in memory`.

The full output:
```
Start checking required NuGet packages...
Checking 'Microsoft.EntityFrameworkCore.SqlServer' NuGet Package...
Checking 'Microsoft.EntityFrameworkCore.Tools' NuGet Package...
Checking 'Microsoft.AspNetCore.Identity.UI' NuGet Package...
Checking 'Microsoft.AspNetCore.Identity.EntityFrameworkCore' NuGet Package...
Checking 'Microsoft.VisualStudio.Web.CodeGeneration.Design' NuGet Package...
Building project 'Gnomeshade.WebApi'...
Check and install Code Generation tool...
Start scaffolding 'Identity'...
Running command: C:\Gnomeshade\source\Gnomeshade.WebApi\obj\dotnet-aspnet-codegenerator.exe --project C:\Gnomeshade\source\Gnomeshade.WebApi\Gnomeshade.WebApi.csproj --target-framework net7.0 --configuration "Release" --no-build identity --dbContext Gnomeshade.Data.Identity.IdentityContext --files "Account.Login" --layout ~/Views/Shared/_Layout.cshtml
Finding the generator 'identity'...
Running the generator 'identity'...
Failed to compile the project in memory
C:\Gnomeshade\source\Gnomeshade.WebApi\V1\Importing\Paperless\Rimi\RimiPurchaseIdentifier.cs(70,31): error CS8795: Partial method 'RimiPurchaseIdentifier.PriceRegex()' must have an implementation part because it has accessibility modifiers.
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
RunTime 00:00:04.95
Scaffolding 'Identity' has finished with errors:
 * Scaffold item command has finished with error: Failed to compile the project in memoryC:\Gnomeshade\source\Gnomeshade.WebApi\V1\Importing\Paperless\Rimi\RimiPurchaseIdentifier.cs(70,31): error CS8795: Partial method 'RimiPurchaseIdentifier.PriceRegex()' must have an implementation part because it has accessibility modifiers.
```

And the code causing the error
```csharp
public sealed partial class RimiPurchaseIdentifier
{
    [GeneratedRegex(@"\d{1,},\d{2}", RegexOptions.IgnoreCase)]
    private static partial Regex PriceRegex();
}
```

Also seems similar to #1552, but that one did not mention source generators.

### Further technical details
Microsoft.VisualStudio.Web.CodeGeneration.Design version 7.0.4
dotnet --version 7.0.102

**Comment by VMelnalksnis** [comment]
It is possible to work around this by commenting out all the partial methods, and all the code referencing those partial methods, etc. However with the push towards source generation in `System.Text.Json`, `System.Text.RegularExpressions` and `Microsoft.Extensions.Logging` soon you will pretty much have to comment out the whole project just to scaffold the pages.

**Comment by deepchoudhery** [comment]
Hmmm I'll take a look, got to be a better way, maybe a fix to support this scenario. I'll reach back soon.

**Comment by manuel-rw** [comment]
I'm having the same issue.
I use compile-time logging source generation, which requires partial classes and methods: https://learn.microsoft.com/en-us/dotnet/core/extensions/logger-message-generator . Removing all methods is a workaround, but requires much work in bigger projects.

**Comment by 3x3y3z3t** [comment]
I'm having the same issue, in VS2022 and .NET 6.

In my project it is from [`System.Text.Json`'s source generation](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation). 
The error message said "SourceGenerationContext does not implement abstract member `JsonSerializerContext.GetTypeInfo(Type)`", and "SourceGenerationContext does not contains definition for `Default`". Both of the above should be generated by source generator.

Reproducing the issue is fairly simple:
1. Create an empty "ASP.NET Web App" project with "Individial Account" authentication and using .NET 6.
2. Create a class to serialize:
```cs
public class WeatherForecast
{
    // add any property;
}
```
3. Create a custom JsonSerializerContext:
```cs
[JsonSerializable(typeof(WeatherForecast))]
internal partial class SourceGenerationContext : JsonSerializerContext
{ }
```
4. Now try scaffolding any Identity page and the error message will appear. You don't need to use the custom JsonSerializer.

**Comment by zacuke** [comment]
I ran into this issue and had to comment out my GeneratedRegex. Is there a more appropriate fix for this?
```
        //[GeneratedRegex(@"(?<=['""])/WebPortal/")]
        //private static partial Regex FixWebPortalPath();
```

**Comment by DanielStout5** [comment]
Having the same issue. For me this throws a very generic InvalidOperationException with no details - quite tricky to track down!
