### ISSUE TITLE
Correct usage of  --databaseProvider|-dbProvider option

### ISSUE THREAD

**Issue by AlexZeitler** [dotnet/Scaffolding#2345]
## Ask a question

Using `dotnet-aspnet-codegenerator` version `7.0.5.` I tried to use the `-dbProvider` option with a value of `postgres`

```bash
Selected Code Generator: identity

Generator Options:
  --dbContext|-dc                : Name of the DbContext to use, or generate (if it does not exist).
  --files|-fi                    : List of semicolon separated files to scaffold. Use the --listFiles option to see the available options.
  --listFiles|-lf                : Lists the files that can be scaffolded by using the '--files' option.
  --userClass|-u                 : Name of the User class to generate.
  --databaseProvider|-dbProvider : Database provider to use. Options include 'sqlserver' (default), 'sqlite', 'cosmos', 'postgres'.
  --force|-f                     : Use this option to overwrite existing files.
  --useDefaultUI|-udui           : Use this option to setup identity and to use Default UI.
  --layout|-l                    : Specify a custom layout file to use.
  --generateLayout|-gl           : Use this option to generate a new _Layout.cshtml
  --bootstrapVersion|-b          : Specify the bootstrap version. Valid values: '3', '4'. Default is 4.
  --useSqLite|-sqlite            : Flag to specify if DbContext should use SQLite instead of SQL Server.
```

This is is the command used and the output:

```bash
dotnet aspnet-codegenerator identity -dc IdentityDbContext -u AppUser -f -gl -dbProvider postgres
Building project ...
Finding the generator 'identity'...
Running the generator 'identity'...
Invalid database provider 'postgres' found.
Supported database providers include : 'System.Collections.Generic.KeyValuePair`2[System.String,Microsoft.DotNet.Scaffolding.Shared.DbProvider][]', 0', 1' and '[SQLite, SQLite]'
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
RunTime 00:00:14.32
```

What's the right way to use the `-dbProvider` option with values other than `sqlserver`?

```bash
 dotnet --info
.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /home/alexzeitler/.dotnet/sdk/7.0.102/

Host:
  Version:      7.0.2
  Architecture: x64
  Commit:       d037e070eb

.NET SDKs installed:
  6.0.405 [/home/alexzeitler/.dotnet/sdk]
  7.0.102 [/home/alexzeitler/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.13 [/home/alexzeitler/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [/home/alexzeitler/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.13 [/home/alexzeitler/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [/home/alexzeitler/.dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/home/alexzeitler/.dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by deepchoudhery** [comment]
Hey,
For scaffolding identity, only `sqlserver` and `sqlite` are supported.
I'll change the help for identity to reflect that clearly.

**Comment by AlexZeitler** [comment]
@deepchoudhery Thanks for clarification

**Comment by pablotdv** [comment]
I had the same error using sqlite as database provider
