### ISSUE TITLE
length ('-639') must be a non-negative value dotnet aspnet-codegenerator identity

### ISSUE THREAD

**Issue by bukowa** [dotnet/Scaffolding#3045]
```C#
$ dotnet aspnet-codegenerator identity -dbProvider sqlite
Building project ...
Finding the generator 'identity'...
Running the generator 'identity'...
length ('-639') must be a non-negative value. (Parameter 'length')
Actual value was -639.
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
RunTime 00:00:32.26
```

**Comment by bukowa** [comment]
`aspnet-codegenerator identity` won't work when your application is using `class Program static Run(string[] args)` top level statement
Adding this code causes the error
 ![Image](https://github.com/user-attachments/assets/6f37f77a-2396-41dd-a9a7-8047397f2e9b)
incompatible

**Comment by deepchoudhery** [comment]
Will take a look at this bug soon but for a workaround, please try our new command-line scaffolding tool, [dotnet-scaffold](https://www.nuget.org/packages/Microsoft.dotnet-scaffold/9.0.0-preview.9.24509.5)
