### ISSUE TITLE
Scaffolding fails if the user project contains 'unsafe' code

### ISSUE THREAD

**Issue by prafullbhosale** [dotnet/Scaffolding#639]
If the user project has any `unsafe` code, scaffolding fails to get the in memory compilation using Roslyn. 

Sample code for repro: 
https://github.com/prafullbhosale/UnsafeSample

Run 
```
dotnet aspnet-codegenerator view Index List -m UnsafeSample.Models.Car -outDir Views\Cars\
```

Scaffolding fails with the below error: 

```
Building project ...
Finding the generator 'view'...
Running the generator 'view'...
Could not get the reflection type for Model : Car
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
RunTime 00:00:08.17
```

**Comment by deepchoudhery** [comment]
fixed for dotnet-scaffold, closing., please use the new 'dotnet-scaffold' tool. Blog [here](https://devblogs.microsoft.com/dotnet/introducing-dotnet-scaffold/)
