### ISSUE TITLE
aspnet-codegenerator identity scaffoling failure on macOS

### ISSUE THREAD

**Issue by anorborg** [dotnet/Scaffolding#927]
## Steps to reproduce:
1) `dotnet new mvc -o Project1`
2) Follow .Net CLI instructions here: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&tabs=netcore-cli#scaffold-identity-into-an-mvc-project-without-existing-authorization
3) from instructions run at Project1 folder `dotnet aspnet-codegenerator identity -h`

## Expected behavior:
Scaffolding works

## Actual behavior:
Scaffolding Errors, trace below:
```
[Trace]: Command Line: identity -h
Scaffolding failed.
No such file or directory


Usage: aspnet-codegenerator [arguments] [options]

Arguments:
  generator  Name of the generator. Check available generators below.

Options:
  -p|--project             Path to .csproj file in the project.
  -n|--nuget-package-dir
  -c|--configuration       Configuration for the project (Possible values: Debug/ Release)
  -tfm|--target-framework  Target Framework to use. (Short folder name of the tfm. eg. net46)
  -b|--build-base-path
  --no-build

[Trace]:    at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setUser, UInt32 userId, UInt32 groupId, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean shouldThrow)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.Extensions.Internal.Command.Execute() in /_/src/Shared/Cli.Utils/Command.cs:line 74
   at Microsoft.Extensions.ProjectModel.MsBuildProjectContextBuilder.Build() in /_/src/Ext.ProjectModel.MsBuild.Sources/MsBuildProjectContextBuilder.cs:line 42
   at Microsoft.VisualStudio.Web.CodeGeneration.Tools.Program.<>c__DisplayClass19_0.<Execute>b__0() in /_/src/dotnet-aspnet-codegenerator/Program.cs:line 126
RunTime 00:00:00.09
```

#### dotnet --info
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.500
 Commit:    b68b931422

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.500/

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  2.1.402 [/usr/local/share/dotnet/sdk]
  2.1.403 [/usr/local/share/dotnet/sdk]
  2.1.500 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

#### Project File
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <RootNamespace>Project1.Server</RootNamespace>
    <AssemblyName>Project1.Server</AssemblyName>
    <LangVersion>latest</LangVersion>
    <UserSecretsId>secret-xxxxxxx</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.1.2" PrivateAssets="All" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.6" />
  </ItemGroup>

</Project>
```

**Comment by Rick-Anderson** [comment]
@anorborg  I've had a few folks report this and they forgot to CD to the project directory. Are you still able to reproduce this problem?

**Comment by ananthakrishnands** [comment]
I am facing an issue when i CD into the project directory. Any pointers to resolve it?
Error::
Selected Code Generator: identity
No code generator found with the name 'identity'.

**Comment by deepchoudhery** [comment]
fixed for dotnet-scaffold, closing., please use the new 'dotnet-scaffold' tool. Blog [here](https://devblogs.microsoft.com/dotnet/introducing-dotnet-scaffold/)
